name: 'bundle Stable Diffusion wildcards'
description: 'Stable Diffusion wildcards'
author: 'bluelovers'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  paths:
    description: 'List of file paths. Each file path must be on a newline.'
    required: true
  outputFile:
    description: 'outputFile path'
    required: true
  autoCreateOutputDir:
    description: 'auto create outputFile path'
  allowMultiRoot:
    description: 'wildcards allowMultiRoot'
  disableUnsafeQuote:
    description: 'wildcards disableUnsafeQuote'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
